### Login request to retrive token

POST http://lb-d398c272.elb.localhost.localstack.cloud:4004/auth/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}
> {% client.global.set("token", response.body.token) %}